import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Button from "../components/Button";
import FeatureItem from "../components/FeatureItem";
import GridItem from "../components/GridItem";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Slider from "../components/Slider";
import QuestionItem from "../components/QuestionItem";
import ProductList from "../containers/ProductList";
import Footer from "../components/Footer";
import { Fragment } from "react";
import { gridItem, questionItem } from "../untils/contants";
import styles from "../styles/home.module.scss";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.home}>
      <Head>
        <title>
          Free Background Image Remover: Remove BG from HD Images Online -
          Erase.bg
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preload" href="/videos/hero_video.m4v" as="videos" />
      </Head>
      <Header />
      <Hero />
      <main>
        <section className={styles.intro}>
          <h3>Get Erase.bg mobile app</h3>
          <p>
            Remove background from images for free with the all new Erase.bg
            mobile app
          </p>
          <div className={styles.intro__apps}>
            <Link href="/">
              <a className={styles.icon}>
                <img src="/images/google_play.png" alt="google_play" />
              </a>
            </Link>
            <Link href="/">
              <a className={styles.icon}>
                <img src="/images/app_store.png" alt="app_store" />
              </a>
            </Link>
          </div>
        </section>
        <section className={styles.experience}>
          <div className={styles.container}>
            <h3 className={styles.title}>
              Experience the Accuracy of AI Background Removal
            </h3>
            <p className={styles.para}>
              Slide to see how the background is removed with precision
            </p>
            <Slider />
          </div>
        </section>
        <section className={styles.features}>
          <div className="container">
            <h3 className={styles.title}>Possibilities are Endless</h3>
            <p className={styles.para}>
              Remove Background for profile pictures, social media graphics,
              eSignatures, company logos, presentations and more using our smart
              editing, resizing and exporting tools
            </p>
            <FeatureItem
              title="Creative Profile Pictures"
              imagesUrl="/images/profile-pictures.png"
            >
              Create custom WhatsApp display pictures with gradients and
              patterns. Boost your social media likes by flaunting your
              creativity. Get the right image format for government documents
              and passport
              <div style={{ marginTop: "28px" }}>
                <Button size="medium" downLoad handClick={() => {router.push("/upload")}}>Upload Image</Button>
              </div>
            </FeatureItem>
            <FeatureItem
              title="Signatures & Logos"
              imagesUrl="/images/signatures.png"
              reverse
            >
              Quickly remove background from logos and signatures for your
              online documents
              <div style={{ marginTop: "28px" }}>
                <Button size="medium" downLoad handClick={() => {router.push("/upload")}}>Upload Image</Button>
              </div>
            </FeatureItem>
          </div>
        </section>
        <section className={`${styles.grid}`}>
          <div className={styles.grid__title}>
            <h3>Built for Everyone</h3>
            <p>
              Whether you work in the creative space or in tech, Erase.bg will
              help you save a lot of time
            </p>
          </div>
          <div className={`${styles.grid__layout} container`}>
            {gridItem.map((item, index) => {
              return (
                <Fragment key={index}>
                  <GridItem item={item} />
                </Fragment>
              );
            })}
          </div>
          <div className={styles.grid__button}>
            <Button size="medium" downLoad>Know more</Button>
          </div>
        </section>
        <section className={styles.products}>
          <ProductList />
        </section>
        <section className={styles.questions}>
          <div className="container">
            <h3 className={styles.questions__title}>
              <span>Frequently</span> Asked Questions
            </h3>
            <p className={styles.questions__para}>
              Here, we have listed some of the commonly asked questions from the
              community. If you do not find the information you need, feel free
              to reach out to us at{" "}
              <a href="mailto:support@pixelbin.io?subject=Contact%20Us">
                support@pixelbin.io
              </a>
            </p>
            <div className={styles.questions__list}>
              {questionItem.map((item, index) => {
                return (
                  <Fragment key={index}>
                    <QuestionItem item={item} />
                  </Fragment>
                );
              })}
            </div>
          </div>
        </section>
        <section className={styles.footer}>
          <Footer />
        </section>
      </main>
    </div>
  );
};

export default Home;
